config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:success] = 'Task が正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task が投稿されませんでした'
      render :new
    end
  end

  def edit
   @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end
  
    private

  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>

  <div class="alert alert-
<%= task_type %>
">
<%= task %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TaskList</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
<%= link_to  '新規タスクの追加', new_task_path %>
</li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>TaskList</title>
    
<%= csrf_meta_tags %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      
<%= render 'layouts/flash_tasks' %>


      
<%= yield %>

    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-6 col-md-offset-2 col-md-6 col-lg-offset-3 col-lg-6">

    
<%= form_for(task) do |f| %>

      
<% if task.errors.any? %>

        <div id="error_explanation">
          <ul>
            
<% task.errors.full_messages.each do |task| %>

              <li>
<%= task %>
</li>
            
<% end %>

          </ul>
        </div>
      
<% end %>


      <div class="form-group">
        
<%= f.label :content, 'タスク' %>

        
<%= f.text_field :content, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :status, 'ステータス' %>

        
<%= f.text_field :status, class: 'form-control' %>

      </div>

      
<%= f.submit '投稿', class: 'btn btn-primary' %>

    
<% end %>

  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @task.id %>
 のタスク編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<% if @tasks.any? %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タスク</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      
<% @tasks.each do |task| %>

        <tr>
          <td>
<%= link_to task.id, task %>
</td>
          <td>
<%= task.content %>
</td>
          <td>
<%= task.content %>
</td>
        </tr>
      
<% end %>

    </tbody>
  </table>
  <div>
    

  </div>
<% end %>

<%= link_to '新規タスクの投稿', new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id = 
<%= @task.id %>
 のタスク詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td>
<%= @task.id %>
</td>
  </tr>
  <tr>
    <th>タスク</th>
    <td>
<%= @task.content %>
</td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td>
<%= @task.status %>
</td>
  </tr>
</table>

<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-default' %>

<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>